name: Go Tests

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Run unit tests
        run: go test ./internal/... ./pkg/... -count=1


  opendota-tests:
    env:
      RUN_OPENDOTA_TESTS: "1"
    name: OpenDota API Tests
    runs-on: ubuntu-latest

    # OpenDota — внешний сервис.
    # Если он временно лежит, не хотим блокировать весь CI.
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Run OpenDota integration tests
        run: go test ./tests/opendota -v -count=1